name: Playwright-Android Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
env:
  EMULATOR_TIMEOUT: 700
  OSTYPE: linux
  HW_ACCEL_OVERRIDE: "-accel off"
   
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
#       - name: Install docker engine
#         run: |
#            brew install docker
#            colima start   
           
#       - name: Docker Setup QEMU
#         uses: docker/setup-qemu-action@v2.1.0
        
      - name: Build docker image
        run: docker --privileged build -t playwright .
      
      - name: Initialize container
        run: docker run -td --memory=8g --privileged -e EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT -e OSTYPE=$OSTYPE -e HW_ACCEL_OVERRIDE="$HW_ACCEL_OVERRIDE" --name android playwright

      - name: Prepare emulator & execute the test
        run: |
         docker exec -t --privileged android bash -c "chmod +x start_emu_headless.sh"
         docker exec -t --privileged android bash -c "./start_emu_headless.sh && npm run test"
   #     docker exec -t --privileged android bash -c "emulator @nexus -no-window -no-snapshot -noaudio -no-boot-anim -memory 4096 -no-accel -camera-back none -gpu swiftshader_indirect -show-kernel -debug-kernel -engine qemu2 -qemu -cpu max"
   #     docker exec -t --privileged android bash -c "emulator @nexus -no-window -no-snapshot -noaudio -no-boot-anim -memory 4096 -accel off -camera-back none -gpu host"



    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
