name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Docker
        run: |
            brew update
            brew install --cask docker
        shell: bash
        
      - name: Add Docker to path
        run: |
             echo 'export PATH="/Applications/Docker.app/Contents/Resources/bin:$PATH"' >> ~/.bash_profile
             source ~/.bash_profile
        shell: bash  
        
      - name: Verify Docker installation
        run: |
            docker --version
            docker-compose --version
        shell: bash  

      - name: Build docker image
        run: docker build -t playwright .
        shell: bash

      - name: Initialize container
        run: docker run --privileged -td --name android playwright
        shell: bash

      - name: Prepare emulator & execute the test
        run: |
          docker exec -t --privileged android bash -c "./start_emu_headless.sh && npm run test"
          shell: bash


    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
