name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-docker@v1
        with:
          docker-version: "20.10.8"
          compose-version: "2.0.0"

      - name: Build docker image
        run: docker build -t playwright .

      - name: Initialize container
        run: docker run --privileged -td --name android playwright

      - name: Prepare emulator & execute the test
        run: |
          docker exec -t --privileged android bash -c "./start_emu_headless.sh && npm run test"

    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
