name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 33
  BUILD_TOOLS: 33.0.2
  ANDROID_API_LEVEL: android-$API_LEVEL
  ANDROID_APIS: $ANDROID_TARGET;$ANDROID_ARCH
  ANDROID_BUILD_TOOLS_VERSION: 33.0.2
  ANDROID_EMULATOR_PACKAGE: system-images;android-$API_LEVEL;$ANDROID_TARGET;$ANDROID_ARCH
  ANDROID_PLATFORM_VERSION: platforms;android-$API_LEVEL
  ANDROID_BUILD_TOOLS: build-tools;33.0.2
  ANDROID_SDK_PACKAGES: system-images;android-33;google_apis;x86_64 platforms;android-33 build-tools;33.0.2 platform-tools emulator
   
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Add avdmanager and sdkmanager to PATH
        run: |
           echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin/:$ANDROID_HOME/emulator/:$ANDROID_HOME/tools/bin/:$ANDROID_HOME/platform-tools/:$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS_VERSION}:$ANDROID_HOME/tools/:$ANDROID_HOME/tools/bin:$ANDROID_HOME/emulator/:$ANDROID_HOME/emulator/lib64:$ANDROID_HOME/emulator/lib64/qt/lib" >> $GITHUB_ENV
#          $ANDROID_HOME/cmdline-tools/latest/bin/:
     
      - name: Install Sdk
        run: |
           cd $ANDROID_HOME/cmdline-tools/latest/bin/
           yes Y | ./sdkmanager --licenses 
           yes Y | ./sdkmanager --install $ANDROID_SDK_PACKAGES
  
      - name: Verify
        run: |
            cd $ANDROID_HOME/cmdline-tools/latest/bin/
            echo "no" | ./avdmanager --verbose create avd --force --name "nexus" --device "Nexus 6" -k "system-images;android-33;google_apis;x86_64"
            emulator @nexus -no-window -no-snapshot-load -noaudio -no-boot-anim -memory 2048  -gpu off


#       - name: Build docker image
#         run: docker build -t playwright .
#         shell: bash

#       - name: Initialize container
#         run: docker run --privileged -td --name android playwright
#         shell: bash

#       - name: Prepare emulator & execute the test
#         run: |
#           docker exec -t --privileged android bash -c "./start_emu_headless.sh && npm run test"
#           shell: bash


    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
