name: Playwright-Android Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
env:
  EMULATOR_TIMEOUT: 400
  OSTYPE: linux
  HW_ACCEL_OVERRIDE: "-accel off"
   
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache
        uses: actions/cache@v3.2.6
      
      - name: Install docker engine
        run: |
           brew install docker
           colima start
           
      - name: Build docker image
        run: docker build -t playwright .
      

      - name: Initialize container
        run: docker run -td --privileged -e EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT -e OSTYPE=$OSTYPE -e HW_ACCEL_OVERRIDE="$HW_ACCEL_OVERRIDE" --name android playwright

      - name: Prepare emulator & execute the test
        run: |
          docker exec -t --privileged android bash -c "emulator @nexus -no-window -no-snapshot-load -noaudio -no-boot-anim -memory 4096 -accel off -camera-back none -gpu swiftshader_indirect"
#          docker exec -t --privileged android bash -c "chmod +x start_emu_headless.sh"
#          docker exec -t --privileged android bash -c "./start_emu_headless.sh && npm run test"


    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
