name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Add avdmanager to PATH
        run: echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin/" >> $GITHUB_ENV
  
      - name: Verify
        env:
          EMULATOR_NAME: nexus
          EMULATOR_DEVICE: Nexus 6
          ANDROID_EMULATOR_PACKAGE: system-images;android-33;google_apis_playstore;x86_64
        run: |
            echo "no" | avdmanager --verbose create avd --force --name "$EMULATOR_NAME" --device "$EMULATOR_DEVICE" --package "$ANDROID_EMULATOR_PACKAGE"
            emulator @nexus -no-window -no-snapshot-load -noaudio -no-boot-anim -memory 2048  -gpu off

#       - name: Build docker image
#         run: docker build -t playwright .
#         shell: bash

#       - name: Initialize container
#         run: docker run --privileged -td --name android playwright
#         shell: bash

#       - name: Prepare emulator & execute the test
#         run: |
#           docker exec -t --privileged android bash -c "./start_emu_headless.sh && npm run test"
#           shell: bash


    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30
